In [1]:
library("SeuratDisk")
library("zellkonverter")
library("Seurat")
library(tidyverse)
library(kasumi)

Registered S3 method overwritten by 'SeuratDisk':
  method            from
  as.sparse.H5Group Seurat

Registered S3 method overwritten by 'zellkonverter':
  method                                             from
  py_to_r.pandas.core.arrays.categorical.Categorical reticulate

Lade n"otiges Paket: SeuratObject

Lade n"otiges Paket: sp

'SeuratObject' was built under R 4.4.0 but the current version is
4.4.2; it is recomended that you reinstall 'SeuratObject' as the ABI
for R may have changed


Attache Paket: 'SeuratObject'


Die folgenden Objekte sind maskiert von 'package:base':

    intersect, t


-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
v dplyr     1.1.4     v readr     2.1.5
v forcats   1.0.0     v stringr   1.5.2
v ggplot2   4.0.0     v tibble    3.3.0
v lubridate 1.9.4     v tidyr     1.3.1
v purrr     1.1.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Kasumi is able to run computationally intensive functions
  in parallel. Please consider specifying a future::plan(). For example by running
  future::plan(future::multisession) before calling Kasumi functions.

In [2]:
adata_file <- "/Users/jawadalaaedeen/Desktop/PhD/NMC/results/adata_unified.h5ad"

In [3]:
ad <- readH5AD(adata_file)

Warning message:
"The names of these selected obs columns have been modified to match R
conventions: 'Cell 3D Volume' -> 'Cell.3D.Volume', 'Cell Bbox Bottom' ->
'Cell.Bbox.Bottom', 'Cell Bbox Left' -> 'Cell.Bbox.Left', 'Cell Bbox Right' ->
'Cell.Bbox.Right', 'Cell Bbox Top' -> 'Cell.Bbox.Top', 'Cell Bbox X Size' ->
'Cell.Bbox.X.Size', 'Cell Bbox Y Size' -> 'Cell.Bbox.Y.Size', 'Cell Center X'
-> 'Cell.Center.X', 'Cell Center Y' -> 'Cell.Center.Y', 'Cell Center Y
Inverted' -> 'Cell.Center.Y.Inverted', 'Cell Contour Bending Energy' ->
'Cell.Contour.Bending.Energy', 'Cell Contour Length' -> 'Cell.Contour.Length',
'Cell Convex Hull Area' -> 'Cell.Convex.Hull.Area', 'Cell Convex Hull
Perimeter' -> 'Cell.Convex.Hull.Perimeter', 'Cell Convexity' ->
'Cell.Convexity', 'Cell Cytoplasm Area' -> 'Cell.Cytoplasm.Area', 'Cell Feret
Diameter Max' -> 'Cell.Feret.Diameter.Max', 'Cell Feret Diameter Maximum Angle'
-> 'Cell.Feret.Diameter.Maximum.Angle', ..., 'site of biopsy/resection for
MACSima sample' -> 'site.of.biopsy.resection.for.MACSima.sample', and 'MACSima
sample type' -> 'MACSima.sample.type'"

In [4]:
ad_seurat <- as.Seurat(ad, counts = "X", data = NULL)

Warning message:
"`PackageCheck()` was deprecated in SeuratObject 5.0.0.
i Please use `rlang::check_installed()` instead.
i The deprecated feature was likely used in the Seurat package.
  Please report the issue at <https://github.com/satijalab/seurat/issues>."

In [5]:
patient_exps <- ad_seurat@meta.data %>%
pull(patient_exp) %>%
unique()

cts <- ad_seurat@meta.data %>%
pull(cell_type) %>%
unique()

all.cells.ctcl <- patient_exps %>% map(\(id){
ad_seurat@meta.data %>%
filter(patient_exp == id) %>%
pull(cell_type) %>%
map(~ .x == cts) %>%
rlist::list.rbind() %>%
`colnames<-`(make.names(cts)) %>%
as_tibble(.name_repair = "unique")
})
names(all.cells.ctcl) <- patient_exps

all.positions.ctcl <- patient_exps %>% map(\(id){
ad_seurat@meta.data %>%
filter(patient_exp == id) %>%
select(Cell.Center.X, Cell.Center.Y) %>%
`colnames<-`(c("x", "y"))
})
names(all.positions.ctcl) <- patient_exps

In [6]:
as.character(patient_exps) %>% walk(\(id){
ct <- all.cells.ctcl[[id]]
pos <- all.positions.ctcl[[id]]
kasumi.views <- create_initial_view(ct) %>% add_paraview(pos, 20, family = "constant", prefix="p.")
suppressWarnings(
run_kasumi(kasumi.views, pos, window=400, overlap=50, id, "CTCLct400.sqm", minu=20, bypass.intra=TRUE, sqlite_timeout = 250)
)
})

Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding


Generating paraview using 20 nearest neighbors per unit


Sliding

In [6]:
options(future.globals.maxSize = 5 * 1024^3)  # 5 GB

In [7]:
getwd()

[1] "/Users/jawadalaaedeen/Desktop/PhD/NMC/NMC_spatial/R"

In [ ]:
kasumi.results <- collect_results("/Users/jawadalaaedeen/Desktop/PhD/NMC/results/CTCLct400.sqm")

Collecting improvements


Collecting contributions


Collecting importances

In [68]:
# First representation - relationships
kasumi.representation <- extract_representation(kasumi.results)
# Second representation - clusters
kasumi.clusters <- extract_clusters(kasumi.representation, "leiden", 0.4, 0.9)
# Cluster composition
kasumi.agg <- aggregate_clusters(kasumi.clusters)
# Third representation - persistent cluster composition -
# clusters that are present in at least 5 samples
persistent.clusters <- persistent_clusters(kasumi.agg, 5)
kasumi.persistent <- kasumi.agg %>% select(id, all_of(persistent.clusters))

New names:
* `` -> `...1`
* `` -> `...2`
* `` -> `...3`
* `` -> `...4`
* `` -> `...5`
* `` -> `...6`
* `` -> `...7`
* `` -> `...8`
* `` -> `...9`
* `` -> `...10`
* `` -> `...11`
* `` -> `...12`
* `` -> `...13`
* `` -> `...14`
* `` -> `...15`
* `` -> `...16`
* `` -> `...17`
* `` -> `...18`
* `` -> `...19`
* `` -> `...20`
* `` -> `...21`
* `` -> `...22`
* `` -> `...23`
* `` -> `...24`
* `` -> `...25`
* `` -> `...26`
* `` -> `...27`
* `` -> `...28`
* `` -> `...29`
* `` -> `...30`
* `` -> `...31`
* `` -> `...32`
* `` -> `...33`
* `` -> `...34`

In [99]:
kasumi.views

$intraview
# A tibble: 17,398 x 18
   Tumor_cells NFC   M1_macrophages MDSCs Actin._cells M1_M2_macrophages
   <lgl>       <lgl> <lgl>          <lgl> <lgl>        <lgl>
 1 TRUE        FALSE FALSE          FALSE FALSE        FALSE
 2 FALSE       TRUE  FALSE          FALSE FALSE        FALSE
 3 FALSE       FALSE TRUE           FALSE FALSE        FALSE
 4 FALSE       FALSE FALSE          TRUE  FALSE        FALSE
 5 TRUE        FALSE FALSE          FALSE FALSE        FALSE
 6 FALSE       FALSE FALSE          FALSE TRUE         FALSE
 7 FALSE       FALSE TRUE           FALSE FALSE        FALSE
 8 FALSE       FALSE FALSE          FALSE TRUE         FALSE
 9 FALSE       FALSE FALSE          FALSE TRUE         FALSE
10 FALSE       FALSE FALSE          FALSE TRUE         FALSE
# i 17,388 more rows
# i 12 more variables: CD8._T_cells <lgl>, Lymphatic_endothelial_cells <lgl>,
#   CD4._T_cells <lgl>, M2_macrophages <lgl>, Endothelial_cells <lgl>,
#   Granulocytes <lgl>, Treg_T_cells <lgl>, DCs <lgl>, B_cells <lgl>,
#   Plasma_cells <lgl>, Mast_cells <lgl>, NK_cells <lgl>

$misty.uniqueid
[1] "eac2ed4dceb7f2e04701f654a2000104"

$paraview.10
     p.Tumor_cells p.NFC p.M1_macrophages p.MDSCs p.Actin._cells
1                8     1                0       0              1
2                7     1                0       0              2
3                3     1                0       2              4
4                4     1                1       0              3
5                3     1                0       1              4
6                5     1                1       0              2
7                2     0                0       0              8
8                3     0                1       0              6
9                4     0                1       0              5
10               5     1                0       0              4
11               5     1                0       0              4
12               6     0                0       0              4
13               5     0                0       0              5
14               8     0                0       0              2
15               6     0                0       0              4
16               2     0                0       2              6
17               2     0                0       2              6
18               5     0                0       0              5
19               4     0                0       1              5
20               4     0                0       1              5
21               2     0                0       0              8
22               3     0                1       2              4
23               2     0                1       1              6
24               6     1                0       0              3
25               6     1                0       0              3
26               7     1                0       0              2
27               7     1                1       0              1
28              10     0                0       0              0
29              10     0                0       0              0
30              10     0                0       0              0
31               9     0                0       0              1
32               8     0                0       0              2
33               8     0                0       0              2
34               9     0                0       0              1
35               9     0                0       0              1
36              10     0                0       0              0
37              10     0                0       0              0
38              10     0                0       0              0
39              10     0                0       0              0
40              10     0                0       0              0
41               9     0                0       0              0
42               8     0                0       0              0
43               6     0                1       0              0
44               7     0                1       0              0
45               6     0                0       0              0
46               2     2                2       0              0
47               3     4                1       1              0
48               1     4                0       1              0
49               4     4                0       0              0
50               7     3                0       0              0
51               9     1                0       0              0
52               8     2                0       0              0
53               9     1                0       0              0
54               9     1                0       0              0
55              10     0                0       0              0
56               8     0                2       0              0
57               6     2                1       0              1
58               6     2                2       0              0
59               8     0                1       1              0
60               9     0                0       1              0
61               9     0                0       1              0
62               8     2                0       0              0
63               6     1                0       1              1
64               8     1                0       0              1
65               7     2                0       0              1
66               8     2                0       0              0
67               9     1                0       0              0
68               9     1                0       0              0
69               9     1                0       0              0
70              10     0                0       0              0
71              10     0                0       0              0
72              10     0                0       0              0
73              10     0                0       0              0
74               9     1                0       0              0
75               9     1                0       0              0
76              10     0                0       0              0
77               9     1                0       0              0
78               9     1                0       0              0
79               9     1                0       0              0
80               7     3                0       0              0
81               7     3                0       0              0
82               7     3                0       0              0
83               8     2                0       0              0
84               9     1                0       0              0
85              10     0                0       0              0
86              10     0                0       0              0
87               9     0                0       0              1
88               8     2                0       0              0
89               3     0                0       0              7
90               3     0                0       0              7
91              10     0                0       0              0
92               5     0                0       0              5
93              10     0                0       0              0
94              10     0                0       0              0
95               9     1                0       0              0
96               9     0                0       0              1
97               9     0                1       0              0
98               9     0                0       1              0
99               5     0                0       1              4
100             10     0                0       0              0
101              8     0                0       0              0
102              6     3                0       0              0
103              7     2                0       0              0
104              5     0                0       0              5
105              9     0                0       0              1
106              9     1                0       0              0
107              6     1                0       0              3
108              4     2                0       0              4
109              1     0                0       0              9
110              0     0                0       0              9
111             10     0                0       0              0
112              8     1                0       0              1
113              1     5                1       1              0
114              6     1                2       0              1
115              8     0                0       0              1
116             10     0                0       0              0
117             10     0                0       0              0
118              9     0                0       0              0
119              7     3                0       0              0
120              9     1                0       0              0
121              9     0                0       0              0
122              7     3                0       0              0
123              9     0                0       1              0
124             10     0                0       0              0
125              6     4                0       0              0
126              9     0                1       0              0
127              6     2                0       1              0
128             10     0                0       0              0
129              9     1                0       0              0
130              3     1                0       1              4
131              2     0                1       2              5
132             10     0                0       0              0
133             10     0                0       0              0
134              9     1                0       0              0
135              0     0                0       2              8
136             10     0                0       0              0
137              3     4                0       1              0
138              6     4                0       0              0
139             10     0                0       0              0
140              4     3                0       0              3
141              5     1                0       1              3
142              9     0                0       0              1
143              3     5                0       0              0
144              8     2                0       0              0
145              5     4                0       0              1
146              8     1                0       1              0
147              6     3                0       0              1
148              7     1                0       0              2
149              8     0                0       0              2
150              0     0                0       0              9
151              6     0                0       0              0
152              9     0                0       0              1
153              5     0                1       0              0
154              7     2                0       1              0
155              7     2                0       0              1
156              3     0                0       2              5
157              2     1                0       0              6
158             10     0                0       0              0
159              2     3                0       1              0
160              8     2                0       0              0
161              8     0                1       1              0
162              6     0                0       0              4
163              6     1                1       0              2
164             10     0                0       0              0
165             10     0                0       0              0
166             10     0                0       0              0
167              0     0                0       2              8
168              0     5                1       1              0
169              4     0                1       2              3
170              2     0                1       0              7
171             10     0                0       0              0
172              5     3                0       0              0
173             10     0                0       0              0
174              3     0                0       0              7
175              1     5                0       1              0
176              5     0                0       1              4
177             10     0                0       0              0
178              4     5                0       0              1
179              4     1                0       1              3
180              4     0                0       0              6
181              5     0                0       0              5
182              2     0                0       2              6
183              7     1                0       1              0
184              3     0                1       1              5
185             10     0                0       0              0
186              9     1                0       0              0
187              2     0                0       3              5
188              7     0                0       0              0
189              3     5                0       0              0
190              6     4                0       0              0
191              9     1                0       0              0
192              0     0                0       1              9
193              8     0                0       0              1
194             10     0                0       0              0
195              8     0                0       0              2
196              8     0                1       1              0
197              8     0                1       1              0
198              3     0                0       0              7
199             10     0                0       0              0
200              0     0                0       0              9
201              8     0                2       0              0
202             10     0                0       0              0
203             10     0                0       0              0
204              2     2                2       0              0
205              7     3                0       0              0
206             10     0                0       0              0
207              7     1                0       0              1
208             10     0                0       0              0
209              9     1                0       0              0
210              6     2                1       0              1
211              9     1                0       0              0
212              5     0                0       1              4
213              3     0                1       2              4
214              8     0                0       0              0
215              9     1                0       0              0
216              4     1                0       0              5
217              5     0                1       0              0
218              9     1                0       0              0
219              5     0                1       0              3
220              9     1                0       0              0
221              9     1                0       0              0
222              4     2                0       0              4
223              9     1                0       0              0
224              4     0                0       1              4
225              1     5                2       0              0
226              7     2                0       0              0
227              5     1                0       0              4
228              2     0                1       0              7
229              9     1                0       0              0
230              6     1                2       0              1
231              8     1                0       0              0
232             10     0                0       0              0
233              8     2                0       0              0
234              9     1                0       0              0
235              7     1                2       0              0
236              6     2                0       1              0
237              4     0                0       0              6
238              7     0                0       0              3
239              6     0                0       0              4
240             10     0                0       0              0
241              9     0                0       1              0
242             10     0                0       0              0
243              8     0                0       0              0
244              9     1                0       0              0
245             10     0                0       0              0
246              7     2                0       0              1
247              5     1                0       0              4
248              7     2                0       0              0
249              8     1                0       1              0
250              8     0                0       0              0
251              2     1                0       0              0
252              6     4                0       0              0
253              8     2                0       0              0
254              9     0                1       0              0
255              3     0                1       1              5
256              3     2                1       0              0
257              6     1                1       0              2
258              7     0                0       0              3
259              4     0                0       0              0
260              8     2                0       0              0
261              7     0                0       0              2
262              1     5                0       1              0
263              8     0                0       0              2
264             10     0                0       0              0
265              1     1                0       0              7
266              7     0                0       0              3
267             10     0                0       0              0
268             10     0                0       0              0
269              0     0                0       0              9
270              9     0                0       1              0
271              4     5                0       0              1
272              9     0                0       0              1
273              1     4                2       1              0
274              9     1                0       0              0
275             10     0                0       0              0
276              8     2                0       0              0
277              8     1                0       0              0
278              4     0                0       2              4
279             10     0                0       0              0
280              6     0                0       0              2
281              8     0                1       1              0
282              7     0                0       0              3
283              1     0                0       1              8
284             10     0                0       0              0
285              9     1                0       0              0
286              2     1                0       0              7
287              7     2                0       0              0
288             10     0                0       0              0
289              3     0                0       0              7

In [98]:
kasumi.representation

     id           xcenter  ycenter paraview.10_p.Tumor_cells_Tumor_cells
1    NMC_16_ROI19 227.1     205.79 1.323841e+00
2    NMC_16_ROI19 227.1    1205.79 4.254637e-01
3    NMC_16_ROI19 227.1    1405.79 0.000000e+00
4    NMC_16_ROI19 227.1    3805.79 1.234447e+00
5    NMC_16_ROI19 227.1    4005.79 6.588233e-01
6    NMC_16_ROI19 427.1     205.79 7.669969e-01
7    NMC_16_ROI19 427.1    1005.79 2.057998e+00
8    NMC_16_ROI19 427.1    2805.79 2.767869e+00
9    NMC_16_ROI19 427.1    3005.79 2.453778e+00
10   NMC_16_ROI19 427.1    3205.79 1.223470e+00
11   NMC_16_ROI19 427.1    3605.79 5.189764e-01
12   NMC_16_ROI19 427.1    4005.79 2.280307e-01
13   NMC_16_ROI19 427.1    4205.79 1.396654e+00
14   NMC_16_ROI19 627.1     205.79 3.154218e+00
15   NMC_16_ROI19 627.1     405.79 3.250116e+00
16   NMC_16_ROI19 627.1     605.79 2.142079e+00
17   NMC_16_ROI19 627.1     805.79 9.072355e-01
18   NMC_16_ROI19 627.1    1005.79 1.924072e+00
19   NMC_16_ROI19 627.1    2805.79 7.555593e-16
20   NMC_16_ROI19 627.1    3005.79 1.109460e+00
21   NMC_16_ROI19 627.1    3205.79 1.871422e+00
22   NMC_16_ROI19 627.1    3605.79 1.132515e+00
23   NMC_16_ROI19 627.1    4005.79 2.353367e+00
24   NMC_16_ROI19 627.1    4205.79 8.511264e-01
25   NMC_16_ROI19 827.1     205.79 6.716302e-01
26   NMC_16_ROI19 827.1     405.79 2.922699e+00
27   NMC_16_ROI19 827.1    1005.79 6.967700e-01
28   NMC_16_ROI19 827.1    1205.79 2.079454e+00
29   NMC_16_ROI19 827.1    1405.79 6.340781e-01
30   NMC_16_ROI19 827.1    1605.79 1.321983e+00
...  ...          ...      ...     ...
1047 NMC_16_ROI19 11827.10 3605.79 1.4180941
1048 NMC_16_ROI19 11827.10 3805.79 1.9755959
1049 NMC_16_ROI19 11827.10 4005.79 1.7235650
1050 NMC_16_ROI19 12027.10  405.79 2.9177502
1051 NMC_16_ROI19 12027.10  805.79 2.8508649
1052 NMC_16_ROI19 12027.10 1005.79 1.2954060
1053 NMC_16_ROI19 12027.10 1205.79 1.8677068
1054 NMC_16_ROI19 12027.10 1405.79 0.3213724
1055 NMC_16_ROI19 12027.10 2205.79 0.3739874
1056 NMC_16_ROI19 12027.10 2605.79 1.1646155
1057 NMC_16_ROI19 12027.10 2805.79 1.5105516
1058 NMC_16_ROI19 12027.10 3005.79 1.8895488
1059 NMC_16_ROI19 12027.10 3205.79 1.4480286
1060 NMC_16_ROI19 12027.10 3405.79 0.9783187
1061 NMC_16_ROI19 12027.10 3605.79 0.2822729
1062 NMC_16_ROI19 12207.06  205.79 1.3408655
1063 NMC_16_ROI19 12207.06  405.79 0.1958045
1064 NMC_16_ROI19 12207.06  605.79 1.4565603
1065 NMC_16_ROI19 12207.06  805.79 2.0805893
1066 NMC_16_ROI19 12207.06 1005.79 0.0000000
1067 NMC_16_ROI19 12207.06 1205.79 1.6656868
1068 NMC_16_ROI19 12207.06 1405.79 1.3106392
1069 NMC_16_ROI19 12207.06 1605.79 3.0368764
1070 NMC_16_ROI19 12207.06 1805.79 2.3503824
1071 NMC_16_ROI19 12207.06 2005.79 1.8112857
1072 NMC_16_ROI19 12207.06 2205.79 2.3944697
1073 NMC_16_ROI19 12207.06 2405.79 1.9102959
1074 NMC_16_ROI19 12207.06 2605.79 1.2723787
1075 NMC_16_ROI19 12207.06 2805.79 1.3189675
1076 NMC_16_ROI19 12207.06 3005.79 1.2774222
     paraview.10_p.NFC_Tumor_cells paraview.10_p.M1_macrophages_Tumor_cells
1    0.75734020                    1.045971e+00
2    0.06254626                    0.000000e+00
3    0.00000000                    0.000000e+00
4    0.00000000                    0.000000e+00
5    0.00000000                    0.000000e+00
6    0.24891104                    1.626533e-01
7    0.14306444                    0.000000e+00
8    0.68461448                    1.012986e+00
9    0.82547896                    7.985788e-01
10   0.19690368                    4.056990e-01
11   0.31975759                    1.036604e+00
12   0.01570907                    0.000000e+00
13   0.65369800                    0.000000e+00
14   0.79104584                    0.000000e+00
15   0.65899575                    0.000000e+00
16   0.20450844                    4.934228e-01
17   0.01581116                    0.000000e+00
18   0.02026671                    0.000000e+00
19   0.00000000                    1.445363e-16
20   0.00000000                    2.424017e-01
21   0.71757332                    7.576903e-01
22   0.03268723                    6.285216e-01
23   0.70506522                    0.000000e+00
24   0.24332946                    0.000000e+00
25   0.17601409                    2.627237e-02
26   0.48666235                    0.000000e+00
27   0.22555379                    1.703127e-02
28   1.20048912                    0.000000e+00
29   0.62590513                    0.000000e+00
30   0.16998519                    0.000000e+00
...  ...                           ...
1047 0.3137332                     0.29211616
1048 0.6004072                     0.72296135
1049 0.1544286                     0.21765547
1050 1.4920117                     0.19800967
1051 0.4503733                     0.06117392
1052 0.4111194                     0.00000000
1053 0.6108502                     0.00000000
1054 0.1144713                     0.00000000
1055 1.4499073                     0.00000000
1056 0.4207270                     0.50115712
1057 0.5476121                     1.07863873
1058 0.2448717                     0.00000000
1059 0.0000000                     0.66375177
1060 0.3460808                     0.55943759
1061 0.0913184                     0.06566265
1062 1.4008974                     0.26455802
1063 0.1154562                     0.04565634
1064 0.3033216                     0.25456504
1065 0.7877714                     0.45844483
1066 0.0000000                     0.00000000
1067 0.6196131                     0.00000000
1068 1.4211077                     0.00000000
1069 0.9801856                     0.00000000
1070 1.7056300                     0.00000000
1071 0.6552674                     0.00000000
1072 0.7985589                     0.00000000
1073 0.9150274                     0.45564073
1074 0.8810824                     0.17348227
1075 0.4934750                     0.46783689
1076 0.1851249                     0.03955336
     paraview.10_p.MDSCs_Tumor_cells paraview.10_p.Actin._cells_Tumor_cells
1    0.000000e+00                    1.792563e+00
2    5.481633e-02                    1.937562e-01
3    0.000000e+00                    0.000000e+00
4    1.897276e+00                    4.857993e-01
5    1.142437e+00                    1.502635e-01
6    0.000000e+00                    5.731006e-01
7    2.313998e+00                    1.212083e+00
8    1.871562e+00                    6.331097e-01
9    5.237714e-01                    1.141373e+00
10   6.737168e-01                    2.298374e-01
11   5.121524e-01                    2.309965e-01
12   1.455372e-01                    1.192671e-01
13   1.822542e+00                    4.287230e-01
14   4.112863e-01                    1.430408e+00
15   4.915762e-01                    1.038621e+00
16   0.000000e+00                    1.605289e-01
17   0.000000e+00                    1.395881e+00
18   1.790731e+00                    2.405453e+00
19   4.679014e-16                    5.425119e-16
20   9.767741e-01                    4.722465e-01
21   1.394232e+00                    0.000000e+00
22   5.467635e-01                    9.439080e-02
23   1.304253e+00                    1.765856e-01
24   1.737189e-01                    5.845486e-02
25   2.955760e-01                    4.328875e-01
26   1.689461e+00                    8.411226e-01
27   2.649187e-01                    5.564172e-01
28   1.901932e+00                    1.684080e+00
29   3.759464e+00                    1.432301e-01
30   2.905671e+00                    2.868509e-01
...  ...                             ...
1047 0.34170980                      0.17599604
1048 0.29578794                      0.88280842
1049 0.62350268                      0.95296590
1050 0.00000000                      0.38133478
1051 0.00000000                      1.99339087
1052 0.00000000                      2.33146247
1053 0.00000000                      2.57686557
1054 0.03793737                      0.76795756
1055 0.32950022                      0.78967169
1056 0.47331526                      0.28507793
1057 0.05431031                      1.43258505
1058 0.03976079                      0.98702015
1059 0.00000000                      1.64815945
1060 0.62523846                      0.83646089
1061 0.30178929                      0.13728153
1062 0.00000000                      0.58539630
1063 0.00000000                      0.10101899
1064 0.00000000                      1.39939978
1065 0.00000000                      2.08414914
1066 0.00000000                      0.00000000
1067 0.01221107                      1.00143860
1068 0.15629999                      0.66795863
1069 0.00000000                      1.01809214
1070 0.00000000                      2.09055179
1071 0.00000000                      1.89201505
1072 0.00000000                      1.91147286
1073 0.00000000                      1.01473129
1074 0.06115248                      0.16284746
1075 0.19868319                      0.08771651
1076 0.34411741                      0.03060332
     paraview.10_p.M1_M2_macrophages_Tumor_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0
20   0
21   0
22   0
23   0
24   0
25   0
26   0
27   0
28   0
29   0
30   0
...  ...
1047 0.00000000
1048 0.00000000
1049 0.00000000
1050 0.00000000
1051 0.00000000
1052 0.00000000
1053 0.00000000
1054 0.00000000
1055 0.00000000
1056 0.00000000
1057 0.00000000
1058 0.00000000
1059 0.64383500
1060 1.08595681
1061 0.17667394
1062 0.00000000
1063 0.00000000
1064 0.00000000
1065 0.00000000
1066 0.00000000
1067 0.00000000
1068 0.00000000
1069 0.00000000
1070 0.00000000
1071 0.00000000
1072 0.00000000
1073 0.00000000
1074 0.01561984
1075 0.33060708
1076 0.00000000
     paraview.10_p.CD8._T_cells_Tumor_cells ...
1    0                                      ...
2    0                                      ...
3    0                                      ...
4    0                                      ...
5    0                                      ...
6    0                                      ...
7    0                                      ...
8    0                                      ...
9    0                                      ...
10   0                                      ...
11   0                                      ...
12   0                                      ...
13   0                                      ...
14   0                                      ...
15   0                                      ...
16   0                                      ...
17   0                                      ...
18   0                                      ...
19   0                                      ...
20   0                                      ...
21   0                                      ...
22   0                                      ...
23   0                                      ...
24   0                                      ...
25   0                                      ...
26   0                                      ...
27   0                                      ...
28   0                                      ...
29   0                                      ...
30   0                                      ...
...  ...
1047 0.00000000                             ...
1048 0.00000000                             ...
1049 0.98981011                             ...
1050 0.00000000                             ...
1051 0.00000000                             ...
1052 0.08349534                             ...
1053 0.00000000                             ...
1054 0.00000000                             ...
1055 0.00000000                             ...
1056 0.00000000                             ...
1057 0.00000000                             ...
1058 0.00000000                             ...
1059 0.00000000                             ...
1060 0.00000000                             ...
1061 0.00000000                             ...
1062 0.00000000                             ...
1063 0.00000000                             ...
1064 0.00000000                             ...
1065 0.00000000                             ...
1066 0.00000000                             ...
1067 0.04424280                             ...
1068 0.00000000                             ...
1069 0.00000000                             ...
1070 0.00000000                             ...
1071 0.00000000                             ...
1072 0.00000000                             ...
1073 0.00000000                             ...
1074 0.00000000                             ...
1075 0.00000000                             ...
1076 0.00000000                             ...
     paraview.10_p.Plasma_cells_Endothelial_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0
20   0
21   0
22   0
23   0
24   0
25   0
26   0
27   0
28   0
29   0
30   0
...  ...
1047 0
1048 0
1049 0
1050 0
1051 0
1052 0
1053 0
1054 0
1055 0
1056 0
1057 0
1058 0
1059 0
1060 0
1061 0
1062 0
1063 0
1064 0
1065 0
1066 0
1067 0
1068 0
1069 0
1070 0
1071 0
1072 0
1073 0
1074 0
1075 0
1076 0
     paraview.10_p.NK_cells_Endothelial_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0
20   0
21   0
22   0
23   0
24   0
25   0
26   0
27   0
28   0
29   0
30   0
...  ...
1047 0
1048 0
1049 0
1050 0
1051 0
1052 0
1053 0
1054 0
1055 0
1056 0
1057 0
1058 0
1059 0
1060 0
1061 0
1062 0
1063 0
1064 0
1065 0
1066 0
1067 0
1068 0
1069 0
1070 0
1071 0
1072 0
1073 0
1074 0
1075 0
1076 0
     paraview.10_p.Tumor_cells_Plasma_cells paraview.10_p.NFC_Plasma_cells
1    0                                      0
2    0                                      0
3    0                                      0
4    0                                      0
5    0                                      0
6    0                                      0
7    0                                      0
8    0                                      0
9    0                                      0
10   0                                      0
11   0                                      0
12   0                                      0
13   0                                      0
14   0                                      0
15   0                                      0
16   0                                      0
17   0                                      0
18   0                                      0
19   0                                      0
20   0                                      0
21   0                                      0
22   0                                      0
23   0                                      0
24   0                                      0
25   0                                      0
26   0                                      0
27   0                                      0
28   0                                      0
29   0                                      0
30   0                                      0
...  ...                                    ...
1047 0                                      0
1048 0                                      0
1049 0                                      0
1050 0                                      0
1051 0                                      0
1052 0                                      0
1053 0                                      0
1054 0                                      0
1055 0                                      0
1056 0                                      0
1057 0                                      0
1058 0                                      0
1059 0                                      0
1060 0                                      0
1061 0                                      0
1062 0                                      0
1063 0                                      0
1064 0                                      0
1065 0                                      0
1066 0                                      0
1067 0                                      0
1068 0                                      0
1069 0                                      0
1070 0                                      0
1071 0                                      0
1072 0                                      0
1073 0                                      0
1074 0                                      0
1075 0                                      0
1076 0                                      0
     paraview.10_p.MDSCs_Plasma_cells paraview.10_p.Actin._cells_Plasma_cells
1    0                                0
2    0                                0
3    0                                0
4    0                                0
5    0                                0
6    0                                0
7    0                                0
8    0                                0
9    0                                0
10   0                                0
11   0                                0
12   0                                0
13   0                                0
14   0                                0
15   0                                0
16   0                                0
17   0                                0
18   0                                0
19   0                                0
20   0                                0
21   0                                0
22   0                                0
23   0                                0
24   0                                0
25   0                                0
26   0                                0
27   0                                0
28   0                                0
29   0                                0
30   0                                0
...  ...                              ...
1047 0                                0
1048 0                                0
1049 0                                0
1050 0                                0
1051 0                                0
1052 0                                0
1053 0                                0
1054 0                                0
1055 0                                0
1056 0                                0
1057 0                                0
1058 0                                0
1059 0                                0
1060 0                                0
1061 0                                0
1062 0                                0
1063 0                                0
1064 0                                0
1065 0                                0
1066 0                                0
1067 0                                0
1068 0                                0
1069 0                                0
1070 0                                0
1071 0                                0
1072 0                                0
1073 0                                0
1074 0                                0
1075 0                                0
1076 0                                0
     paraview.10_p.CD8._T_cells_Plasma_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0
20   0
21   0
22   0
23   0
24   0
25   0
26   0
27   0
28   0
29   0
30   0
...  ...
1047 0
1048 0
1049 0
1050 0
1051 0
1052 0
1053 0
1054 0
1055 0
1056 0
1057 0
1058 0
1059 0
1060 0
1061 0
1062 0
1063 0
1064 0
1065 0
1066 0
1067 0
1068 0
1069 0
1070 0
1071 0
1072 0
1073 0
1074 0
1075 0
1076 0
     paraview.10_p.Endothelial_cells_Plasma_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0
20   0
21   0
22   0
23   0
24   0
25   0
26   0
27   0
28   0
29   0
30   0
...  ...
1047 0
1048 0
1049 0
1050 0
1051 0
1052 0
1053 0
1054 0
1055 0
1056 0
1057 0
1058 0
1059 0
1060 0
1061 0
1062 0
1063 0
1064 0
1065 0
1066 0
1067 0
1068 0
1069 0
1070 0
1071 0
1072 0
1073 0
1074 0
1075 0
1076 0
     paraview.10_p.Granulocytes_Plasma_cells
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0